### ISSUE TITLE
domready in iframe

### ISSUE THREAD

**Issue by dArignac** [Mediamoose/CeraBox#10]
if I use the cerabox to display an iframe, the domready event within the iframe is fired before the iframe elements are correctly positioned. That probably occured because the iframe is generated with the source and afterwards injected into the container, so that all elements get repositioned (and correctly positioned the first time). I had to add a delay of 1 second to all js code execution in the iframe source that measures elements or determines container positions. Would be nice if you can see forward to fix this somehow, thank you!

**Comment by Mediamoose** [comment]
Hi, thank you for letting us know. Don't think it is possible because of the way it is build. The process of displaying an iframe is; generate iframe element with dimensions 1x1 -> onLoad check sizing options and resize it to the right size -> display iframe. My guess is that domready is fired anywhere between the first two steps while the iframe still has a dimension of 1x1. How about firing you're code onload instead of ondomready? Hope this helps in any way.

**Comment by dArignac** [comment]
Well, firing another event is not that simple as I want to use the existing pages with their js and I don't want them to be adjusted for using in the box. But as this is a possible workaround I'll give it a try!

**Comment by dArignac** [comment]
Well, onload is fired before domready so onload as handler won't work.

**Comment by Mediamoose** [comment]
Hi, domready is fired when the DOM is ready to be used. Onload is fired when all the resource (images, etc.) are loaded. So they're either fired at the same time or domready is first. I believe IE has this mixed up sometimes when onload is fast enough but that is a different story. We will test this soon and hopefully find a solution for you. To be continued.

**Comment by dArignac** [comment]
Thanks!

**Comment by Mediamoose** [comment]
Hi, as promised we looked into it. And you're right, onload is also fired before domready. We can't really change the structure of this but we made an example of how you can manage to get it done. We're starting an advanced example page for specific problems and solutions like this. See http://ceramedia.github.com/CeraBox/#iframe-onload , if you got any questions let us know.
