### ISSUE TITLE
Resize Cerabox

### ISSUE THREAD

**Issue by mmrose** [Mediamoose/CeraBox#11]
Heya,

I'm using Cerabox to display form sites. After saving the form inside the Cerabox, the form size can vary. So I tried to use CeraBoxWindow.updateWindow() to update the size of the Cerabox.

But this simply does not work.

**Comment by Mediamoose** [comment]
Hi,

Thanks for using CeraBox! Please use our support group for questions http://groups.google.com/group/cerabox .

To answer your question, the dynamic resizing only works if the iframe page is from the same domain. And if that page includes the MooTools library. Inspect our local iframe example on our example page to check it out; http://cerabox.net/examples .

Hopefully this answers your question, if you want to discus this more deeply please post it on our support group.

Cheers
