### ISSUE TITLE
iFrame loading problem

### ISSUE THREAD

**Issue by Fiaxhs** [Mediamoose/CeraBox#16]
Hello !

I'm currently implementing cerabox on a project, where I need to open several links in cerabox, within an iframe.

Because of the mootools IFrame implementation, I often timeout.

This happens to me on your own website http://cerabox.net/ clicking the http://google.com iframe example times out and gives an error, because the IFrame is trying to load half of the internet before firing "loaded".

I made a workaround by showing up the iframe right after its creation, and passing width and height, but I thought you might be interested.

**Comment by Mediamoose** [comment]
Hi,

Thanks for your suggestion but we made it this way on purpose, we like the content to be loaded before we show it to the user. Maybe it's a good idea to make the timeout time dynamic by option. This way you could increase the time before the timeout is fired.

The Google examples are not really timed out, Google doesn't allow putting their site in a iframe anymore. We should change those examples to a different site. ;)

Cheers

**Comment by Fiaxhs** [comment]
Ok ! I'll stick with my workaround then :) thanks
